[package]
name = "broot"
version = "1.2.5-dev"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/broot"
documentation = "https://dystroy.org/broot"
description = "A new file manager"
edition = "2018"
keywords = ["cli", "fuzzy", "tree", "search", "regex"]
license = "MIT"
categories = ["command-line-utilities"]
readme = "README.md"
build = "build.rs"
exclude = ["website", "broot*.zip"]

[features]
default = []
client-server = []
clipboard = ["terminal-clipboard"]

[dependencies]
ahash = { version = "0.7", features = ["serde"] }
ansi_colours = "1.0"
base64 = "0.13"
bet = "0.4.0"
char_reader = "0.1"
clap = { version="2.33", default-features=false, features=["suggestions"] }
cli-log = "1.0"
chrono = "0.4"
crossbeam = "0.8"
crossterm = "0.19.0"
custom_error = "1.6"
deser-hjson = "0.1.12"
directories = "2.0"
file-size = "1.0.3"
fnv = "1.0.7"
git2 = { version="0.13", default-features=false }
glob = "0.3"
id-arena = "2.2.1"
image = "0.23.13"
lazy-regex = "0.1.3"
lazy_static = "1.4"
libc = "0.2"
log = "0.4"
minimad = "0.7.0"
open = "1.4"
memmap = "0.7"
pathdiff = "0.1.0"
phf = { version = "0.8", features = ["macros"] }
rayon = "1.5"
regex = "1.3"
secular = "0.2"
serde = { version = "1.0", features = ["derive"] }
splitty = "0.1"
strict = "0.1.4"
syntect = "4.5"
tempfile = "3.1"
termimad = { version = "0.10.0" }
terminal-clipboard = { version = "0.1.1", optional = true }
toml = "0.5"
umask = "1.0"
unicode-width = "0.1.8"


[dev-dependencies]
criterion = "0.3.1"

[target.'cfg(unix)'.dependencies]
lfs-core = "0.3.1"
users = "0.10"

[target.'cfg(windows)'.dependencies]
is_executable = "0.1"

[build-dependencies]
clap = "2.33"

[profile.dev]
debug = false

[profile.release]
debug = false
lto = true # link time optimization - roughly halves the size of the exec
codegen-units = 1 # this removes a few hundred bytes from the final exec size

[[bench]]
name = "fuzzy"
harness = false

[[bench]]
name = "path_normalization"
harness = false

[patch.crates-io]
# bet = { path = "../bet" }
# cli-log = { path = "../cli-log" }
# lazy-regex = { path = "../lazy-regex" }
# minimad = { path = "../minimad" }
# termimad = { path = "../termimad" }
# crossterm = { path = "../crossterm-rs/crossterm" }
# deser-hjson = { path = "../deser-hjson" }
# umask = { path = "../umask" }
# secular = { path = "../secular" }
# strict = { path = "../strict" }
# lfs-core = { path = "../lfs-core" }
