site_name: Broot
site_description: 'Broot, a tree oriented file manager'
site_url: https://dystroy.org/broot
repo_url: https://github.com/Canop/broot
edit_uri: ''

nav:
        - Why: index.md
        - Install:
                - Install broot: install.md
                - Install br: install-br.md
                - Common Problems: common-problems.md
        - Usage:
                - Launch: launch.md
                - Navigation: navigation.md
                - Verbs & Commands: verbs.md
                - Panels: panels.md
                - Staging Area: staging-area.md
                - Tree export: export.md
                - Tips & tricks: tricks.md
                - Reference - The input: input.md
        - Conf:
                - Config file: conf_file.md
                - Verbs and shortcuts: conf_verbs.md
                - Skins: skins.md
                - Icons: icons.md
                - Modal Mode: modal.md
        - Community: community.md

extra_css:
        - css/extra.css
        - css/tab-langs.css


extra_javascript:
        - js/tab-langs.js

theme:
        name: mkdocs
        custom_dir: custom_theme
        highlightjs: true
        hljs_languages:
                - yaml
                - ini
                - css
                - rust

markdown_extensions:
        - admonition
        - def_list
