site_name: Broot
site_description: 'Broot, a tree oriented file manager'
site_url: https://dystroy.org/broot
repo_url: https://github.com/Canop/broot
edit_uri: ''

nav:
        - Why: index.md
        - Install: install.md
        - Usage:
                - Launch: launch.md
                - Navigation: navigation.md
                - Verbs & Commands: verbs.md
                - Panels: panels.md
                - Tree export: export.md
                - Tips & tricks: tricks.md
                - Reference - The input: input.md
        - Conf:
                - Config file: conf_file.md
                - Verbs and shortcuts: conf_verbs.md
                - Skins: skins.md
        - Community: community.md

extra_css:
    - css/extra.css

theme:
        name: mkdocs
        custom_dir: custom_theme
        highlightjs: true
        hljs_languages:
                - yaml
                - rust

markdown_extensions:
        - admonition
        - def_list
