site_name: Broot
site_description: 'Broot, a tree oriented file manager'
site_url: https://dystroy.org/broot
repo_url: https://github.com/Canop/broot
edit_uri: ''

nav:
        - Why: index.md
        - Install: install.md
        - Usage:
                - Launch: launch.md
                - The input: input.md
                - Navigation: navigation.md
                - Verbs & Commands: verbs.md
                - Panels: panels.md
                - Tree Export: export.md
                - Tips & Tricks: tricks.md
        - Conf:
                - Config File: conf_file.md
                - Skins: skins.md
        - Community: community.md

extra_css:
    - css/extra.css

theme:
        name: mkdocs
        custom_dir: custom_theme
        highlightjs: true
        hljs_languages:
                - yaml
                - rust

markdown_extensions:
        - admonition
        - def_list
